Chore/ Docker of Frontend
nccu-cloud-native-group6/pmap pull request #22
Opened 2024-12-15 14:19 UTC by chuang091

2024-12-15 14:35 UTC, chuang091 commented
這個branch 會再開auth的branch把 @Lu-weiting 的東東寫好

2024-12-17 07:32 UTC, Lu-weiting requested changes

2024-12-17 07:32 UTC, Lu-weiting commented on docker-compose-dev.yml
> +      - ${FRONTEND_PORT}:3000
這個你是設多少！在最外圍的env_dev_example中藥補一下

目前後端容器是佔用生產環境素主機的3000了

2024-12-17 08:16 UTC, pj-99 commented
讚讚讚，之後 production 如果有需要優化過的 dockerfile 的話可以參考 next.js 官方提供的這個，build 出來的 image 會比較小
https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/next-app/prod.Dockerfile

2024-12-19 08:33 UTC, merged